spring:
  name: primoserver
  datasource:
    url: jdbc:mysql://localhost:3306/testfinale?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Password123@
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #none
    show-sql: true